project_id = "lqmzujeljkgapnpggpuv"

[functions.create-bots]
verify_jwt = false

[functions.bot-responder]
verify_jwt = false

[functions.generate-bot-photo]
verify_jwt = false

[functions.update-bot-photos]
verify_jwt = false

[functions.cleanup-bots]
verify_jwt = false